repos:
  - repo: https://github.com/FlamingTempura/bibtex-tidy
    rev: v1.11.0
    hooks:
      - id: bibtex-tidy
        name: bibtex-tidy
        entry: bibtex-tidy
        language: node
        types: ["bib"]
        files: "publications.bib"
        args:
          [
            "--v2",
            "--modify",
#            "--output=sources.bib",
            "--omit=issue,venue,institution,ean,language,pmid",
            "--curly",
            "--numeric",
            "--months",
            "--align=17",
#            "--blank-lines",
            "--sort=-year,month,author",
            "--duplicates=key,citation",
            "--no-escape",
            "--sort-fields=title,shorttitle,author,date,year,month,day,journal,journaltitle,fjournal,booktitle,location,on,publisher,address,series,collection,version,volume,number,pages,doi,isbn,issn,url,urldate,abstract,arxiv,eprint,eprintclass,eprinttype,file,copyright,organization,place,numpages,category,groups,readstatus,note,metadata,relevance,priority,ranking,keywords,comment,annotation,creationdate,modificationdate",
            "--trailing-commas",
#            "--no-tidy-comments",
            "--remove-empty-fields",
            "--generate-keys=[auth:required][year:required][duplicateNumber]",
          ]
